GET http://localhost:8080/movies/filterByGenre/Детектив
Accept: application/json

###

GET http://localhost:8080/movies/show
Accept: application/json

###

GET http://localhost:8080/movies/show/1
Accept: application/json

###

POST http://localhost:8080/movies/save
Content-Type: application/json

{
  "title": "Название фильма",
  "releaseYear": "2021",
  "rating": "8.5"
}

###

POST http://localhost:8080/movies/saveWithActors
Content-Type: application/json

{
  "id": 2,
  "title": "Фильм",
  "description": "Комментарий",
  "release": 2003,
  "rating": 10.1,
  "genre": "Мистика",
  "actors": [
    {
      "id": 4,
      "name": "Имя",
      "surname": "Фамилия",
      "role": "Роль",
      "movie_id": 3
    }
  ]
}

###

PUT http://localhost:8080/movies/update/3
Content-Type: application/json

{
"id": 2,
"title": "Фильм",
"description": "Комментарий",
"release": 2003,
"rating": 10.1,
"genre": "Мистика",
"actors": [
{
"id": 4,
"name": "Имя",
"surname": "Фамилия",
"role": "Роль",
"movie_id": 3
}
]
}
